/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as PrevoyanceRouteImport } from './routes/prevoyance'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as PartenairesRouteImport } from './routes/partenaires'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as DevisRouteImport } from './routes/devis'
import { Route as DependanceRouteImport } from './routes/dependance'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AssuranceSanteRouteImport } from './routes/assurance-sante'
import { Route as AssuranceEmprunteurRouteImport } from './routes/assurance-emprunteur'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevoyanceRoute = PrevoyanceRouteImport.update({
  id: '/prevoyance',
  path: '/prevoyance',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const PartenairesRoute = PartenairesRouteImport.update({
  id: '/partenaires',
  path: '/partenaires',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const DevisRoute = DevisRouteImport.update({
  id: '/devis',
  path: '/devis',
  getParentRoute: () => rootRouteImport,
} as any)
const DependanceRoute = DependanceRouteImport.update({
  id: '/dependance',
  path: '/dependance',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceSanteRoute = AssuranceSanteRouteImport.update({
  id: '/assurance-sante',
  path: '/assurance-sante',
  getParentRoute: () => rootRouteImport,
} as any)
const AssuranceEmprunteurRoute = AssuranceEmprunteurRouteImport.update({
  id: '/assurance-emprunteur',
  path: '/assurance-emprunteur',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/assurance-sante': typeof AssuranceSanteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dependance': typeof DependanceRoute
  '/devis': typeof DevisRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/prevoyance': typeof PrevoyanceRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temoignages': typeof TemoignagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/assurance-sante': typeof AssuranceSanteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dependance': typeof DependanceRoute
  '/devis': typeof DevisRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/prevoyance': typeof PrevoyanceRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temoignages': typeof TemoignagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/assurance-emprunteur': typeof AssuranceEmprunteurRoute
  '/assurance-sante': typeof AssuranceSanteRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dependance': typeof DependanceRoute
  '/devis': typeof DevisRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/partenaires': typeof PartenairesRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/prevoyance': typeof PrevoyanceRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temoignages': typeof TemoignagesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/assurance-emprunteur'
    | '/assurance-sante'
    | '/contact'
    | '/cookies'
    | '/dependance'
    | '/devis'
    | '/faq'
    | '/mentions-legales'
    | '/partenaires'
    | '/politique-confidentialite'
    | '/prevoyance'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/temoignages'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/assurance-emprunteur'
    | '/assurance-sante'
    | '/contact'
    | '/cookies'
    | '/dependance'
    | '/devis'
    | '/faq'
    | '/mentions-legales'
    | '/partenaires'
    | '/politique-confidentialite'
    | '/prevoyance'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/temoignages'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/assurance-emprunteur'
    | '/assurance-sante'
    | '/contact'
    | '/cookies'
    | '/dependance'
    | '/devis'
    | '/faq'
    | '/mentions-legales'
    | '/partenaires'
    | '/politique-confidentialite'
    | '/prevoyance'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/temoignages'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  AssuranceEmprunteurRoute: typeof AssuranceEmprunteurRoute
  AssuranceSanteRoute: typeof AssuranceSanteRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DependanceRoute: typeof DependanceRoute
  DevisRoute: typeof DevisRoute
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  PartenairesRoute: typeof PartenairesRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  PrevoyanceRoute: typeof PrevoyanceRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemoignagesRoute: typeof TemoignagesRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prevoyance': {
      id: '/prevoyance'
      path: '/prevoyance'
      fullPath: '/prevoyance'
      preLoaderRoute: typeof PrevoyanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partenaires': {
      id: '/partenaires'
      path: '/partenaires'
      fullPath: '/partenaires'
      preLoaderRoute: typeof PartenairesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/devis': {
      id: '/devis'
      path: '/devis'
      fullPath: '/devis'
      preLoaderRoute: typeof DevisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dependance': {
      id: '/dependance'
      path: '/dependance'
      fullPath: '/dependance'
      preLoaderRoute: typeof DependanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-sante': {
      id: '/assurance-sante'
      path: '/assurance-sante'
      fullPath: '/assurance-sante'
      preLoaderRoute: typeof AssuranceSanteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assurance-emprunteur': {
      id: '/assurance-emprunteur'
      path: '/assurance-emprunteur'
      fullPath: '/assurance-emprunteur'
      preLoaderRoute: typeof AssuranceEmprunteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  AssuranceEmprunteurRoute: AssuranceEmprunteurRoute,
  AssuranceSanteRoute: AssuranceSanteRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DependanceRoute: DependanceRoute,
  DevisRoute: DevisRoute,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  PartenairesRoute: PartenairesRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  PrevoyanceRoute: PrevoyanceRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemoignagesRoute: TemoignagesRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
